### ISSUE TITLE
自由到连vendor目录都帮我们用掉了

### ISSUE THREAD

**Issue by neatstudio** [Tencent/Biny#1]

**Comment by billge1205** [comment]
vendor下的都是用户自定义的 系统库中并不会使用 源码中为demo内容 用户可自行替换和使用

**Comment by hackjan** [comment]
vendor 是composer使用到的目录，用户使用第三方类库会拉取代码到这个目录，这是没考虑到composer的用户。

**Comment by billge1205** [comment]
可以把vendor目录删除 对系统没有什么影响 
另外可以直接将第三方库放入vendor目录下 保持文件名和类名一致的话 Biny中也会完成自动加载 
当然，并不能完全替代composer

**Comment by billge1205** [comment]
仔细考虑了下 是我考虑的不够 已经将用户自定义库改名为extends 谢谢大家提出的意见
