### ISSUE TITLE
为什么类名要带TX前缀

### ISSUE THREAD

**Issue by slince** [Tencent/Biny#10]
这是sf1时代的特色，可以去掉了

**Comment by billge1205** [comment]
只是标明系统库而已 和功能类做区分

**Comment by slince** [comment]
@billge1205  用命名空间区分吧，命名空间不影响速度

**Comment by billge1205** [comment]
嗯 请关注后续更新

**Comment by shiny** [comment]
时刻提醒这是个来自 TX 的感觉可不好。

**Comment by wujunze** [comment]
@slince  请问sf1时代是什么意思?

**Comment by slince** [comment]
@wujunze  symfony 1.x;  差不多php5.2的时候

**Comment by wujunze** [comment]
@slince   哦哦  Thanks

**Comment by baiyutang** [comment]
![image](https://user-images.githubusercontent.com/10782183/56343336-09bc7580-61ed-11e9-99c1-db7da8cfe4d3.png)
我的强迫症都犯了，没必要在每个文件都加一个前缀，这个两个大写缩写放在文件前缀还很难受。
一般前缀或者后缀用来区别或者分类，但是整个库我们已经知道是腾讯的了，就不要在每个文件都加上TX了

**Comment by billge1205** [comment]
@baiyutang 历史遗留问题 原来是php5版本的框架 没有命名空间 只能通过文件名做系统标识
php7之后要做到向下兼容，就没动这一块。
内部使用的框架已经去掉这些命名方式，有时间会整理输出开源（应该会以大版本的方式更新）

**Comment by sn01615** [comment]
重构

**Comment by baiyutang** [comment]
重构的时候喊上我。@sn01615
