### ISSUE TITLE
composer 支持

### ISSUE THREAD

**Issue by terryzwt** [Tencent/Biny#11]
感谢开源这么一个高性能的php框架.
看了一遍,发现不支持composer?这样的话很多php生态圈的库引用起来比较麻烦了.

**Comment by liangyes** [comment]
超轻量级

**Comment by linus-zhou** [comment]
连命名空间都没有，好轻啊

**Comment by billge1205** [comment]
Biny本身定位是不依赖第三库的轻量级框架 也具有自动加载的机制 
放在extends目录下第三方库 Biny也会完成自动加载
但框架本身对comproser支持并不友好 之后对comproser进行更友好的兼容处理 请关注后续更新

**Comment by peinhu** [comment]
KPI项目？打算维护几年

**Comment by billge1205** [comment]
腾讯应该没有KPI开源指标吧 纯粹是好用才分享的 会持续维护更新

**Comment by Echosong** [comment]
既然项目走轻量级就应该支持composer，要不然需求复杂情况只有不停造轮子 。总体看下来真不怎样，带上了腾讯光环而已，实话不如echosong/es这种真正轻量级框架！

**Comment by billge1205** [comment]
谢谢你的建议 也有幸拜读了你的 ES框架 挺有意思的 希望后续能有更多的交流 
Biny会在易用性和性能这两方面持续优化更新
