### ISSUE TITLE
多语言_L似乎有点问题

### ISSUE THREAD

**Issue by ShigemoriHakura** [Tencent/Biny#115]
tpl中使用_L出现报错：<b>Fatal error</b>:  Uncaught Error: Call to undefined function _L()
php7.1，7.4均出现此错误。
下载的是4821b0d203c54e985bc428c81a8a3ad07cf8b4c6这个commit而不是release版本

**Comment by billge1205** [comment]
这里_L 是之前没有命名空间时的写法，其实2.7版本后应该改为 biny\Lib\_L() 但文档没更新
刚刚更新了一下 兼容了 <?=_L('text') ?> 和 <?=biny\Lib\_L('text') ?>两种方式
release的版本会等版本更新一段时间稳定后发布

**Comment by ShigemoriHakura** [comment]
okk
