### ISSUE TITLE
Form的自定义验证问题

### ISSUE THREAD

**Issue by ShigemoriHakura** [Tencent/Biny#119]
https://github.com/Tencent/Biny/blob/master/lib/data/Form.php#L194
按照官网给的form方法，会读不到验证方法。
改为$value[0]时恢复正常。

**Comment by billge1205** [comment]
感谢指正，的确应该是 $value[0] 
你可以提交pr修改 这边会合并到最新版本中

**Comment by ShigemoriHakura** [comment]
提了
