### ISSUE TITLE
部署在IIS7.5老是500错误

### ISSUE THREAD

**Issue by wanghongwu** [Tencent/Biny#124]
发现部署在IIS7.5老是500错误很不稳定，就是页面停留一段时间再刷新就会偶尔500错误

**Comment by billge1205** [comment]
这个环境不是太了解 你可以把php error_report打开 看下具体什么错误 或者看下/log 目录下的error错误信息

**Comment by wanghongwu** [comment]
iis用上aar方向代理到nginx服务上面解决了
