### ISSUE TITLE
加入Restful的OPTIONS默认回复200的开关

### ISSUE THREAD

**Issue by ShigemoriHakura** [Tencent/Biny#133]
在跨域的情况下，前端会先发送一个OPTIONS请求，如果按照OPTIONS_xxx一个一个回那太麻烦了，我现在是在actions里面全局过滤回200，但是我觉得可以做个类似$restful一样的开关，来统一处理特定路径的options请求。

**Comment by billge1205** [comment]
内部使用的Biny 因为不需要option的restful请求，所以跨域是在Controller基类里就把option都拦截了
我想下怎么兼容正常restful请求 晚点更新下

**Comment by billge1205** [comment]
https://github.com/Tencent/Biny/commit/3ca169861bc86cdf4b63e53ae7320a1641f47de5
更新兼容了下跨域功能 在 /config/config.php中进行配置 
allowOrigin 可以是 '*' 或者允许的跨域域名数组 只要满足跨域条件的 options请求都会返回`204 No Content`

**Comment by ShigemoriHakura** [comment]
可以！
