### ISSUE TITLE
请问，使用虚拟主机无法指定 web 为根目录，如何修改？

### ISSUE THREAD

**Issue by wfsdaj** [Tencent/Biny#136]
测试了使用伪静态转发到 web 目录不行：
`RewriteRule ^(.*) web/$1 [L]`

**Comment by billge1205** [comment]
虚拟机应该也能装apache 或者nginx吧 
apache/nginx里可以指定 域名请求的文件根目录 参考这个
http://www.billge.cc/#overview-index

**Comment by wfsdaj** [comment]
感谢回复，是“虚拟主机”不是“虚拟机”，就是没有权限指定“web”为网站根目录的。
