### ISSUE TITLE
可能是我的强迫症比较明显，控制器的基类里这段代码感觉不太好

### ISSUE THREAD

**Issue by limingxinleo** [Tencent/Biny#21]
app/controller/base/baseAction.php
webRoot和CDN_ROOT的命名方式统一一下比较好😊

**Comment by billge1205** [comment]
这个其实是多个项目使用 沉淀下来的 不同的命名方式 之后版本会一起优化掉

**Comment by billge1205** [comment]
两个已合并 原来是区分cdn 和 路径代码的 用户有需要可自行维护
