### ISSUE TITLE
默认SQL文件在框架内吗？

### ISSUE THREAD

**Issue by geekdawns** [Tencent/Biny#25]
默认SQL文件在框架内吗？修改 config之后，提示 sql 报错了，想预览下效果

**Comment by billge1205** [comment]
Biny中没有sql文件这个概念 只需要在/app/config/dns_{env}.php（链接配置）中将数据库库信息配置好即可 表的话需要在dao目录下建立dao文件 或者 在/config/database.php 中建立表映射
初始代码中 应该没有sql语句 如果是你自己写的代码 可以在wiki中看看用法 [http://www.billge.cc/#dao](http://www.billge.cc/#dao) 有不清楚的我会解答

**Comment by geekdawns** [comment]
我是不是可以这样理解，需要自建表，然后“在/app/config/dns_{env}.php（链接配置）中将数据库库信息配置好即可 表的话需要在dao目录下建立dao文件 或者 在/config/database.php 中建立表映射”

**Comment by billge1205** [comment]
恩 是的

**Comment by geekdawns** [comment]
OK,我创建试试。

**Comment by rjzou** [comment]
我建 了Biny_User 表，/login报错 什么问题？

`Fatal error:  method [updateByPk] not exists in [biny\lib\TXSingleDAO] in /Users/rjzou/workspace/php/Biny/lib/models/TXDAO.php:459
Stack trace:
#0 /Users/rjzou/workspace/php/Biny/app/model/person.php(64): biny\lib\TXDAO->__call('updateByPk', Array)
#1 /Users/rjzou/workspace/php/Biny/app/controller/loginAction.php(31): app\model\person->login()
#2 [internal function]: app\controller\loginAction->action_index()
#3 /Users/rjzou/workspace/php/Biny/lib/business/TXController.php(69): call_user_func_array(Array, Array)
#4 /Users/rjzou/workspace/php/Biny/lib/business/TXController.php(42): biny\lib\TXController->call(Object(biny\lib\TXRequest))
#5 /Users/rjzou/workspace/php/Biny/lib/business/TXController.php(105): biny\lib\TXController->execute()
#6 /Users/rjzou/workspace/php/Biny/lib/TXApp.php(177): biny\lib\TXController->dispatcher()
#7 /Users/rjzou/workspace/php/Biny/web/index.php(21): TXApp::run()
#8 {main} `

**Comment by billge1205** [comment]
@rjzou class userDAO extends baseDAO
DAO文件需要自己创建或者配置映射关系

**Comment by rjzou** [comment]
`mysql> desc biny_user;
+----------+-------------+------+-----+---------+-------+
| Field    | Type        | Null | Key | Default | Extra |
+----------+-------------+------+-----+---------+-------+
| id       | int(11)     | NO   | PRI | NULL    |       |
| username | varchar(45) | YES  |     | NULL    |       |
+----------+-------------+------+-----+---------+-------+
2 rows in set (0.00 sec)`


`class userDAO extends baseDAO
{
    protected $table = 'Biny_User';
    protected $_pk = 'id';
    protected $_username = 'username';
    protected $_pkCache = true;
}`


是这样吗？ 那么接下来要怎么用呢？

**Comment by rjzou** [comment]
> [ERROR]2018-09-30 10:33:00:936[::1] /favicon.ico
ERROR CODE: 2001
Action[favicon.icoAction] is not exists.

我新建了testDAO,和在config/database.php

> return array(
    'dbConfig' => array(
        'test' => 'Biny_Test',
        'user' => 'Biny_User'
    )
);
Biny_Test表也建好了。
访问http://localhost:8080/test 还有这个错误？

**Comment by billge1205** [comment]
@rjzou 有文件就不需要在config里配置映射了
配置只是为了只需要基础功能的DAO而不想创建文件时准备的

**Comment by rjzou** [comment]
谢谢，test可以查询出来了。

> 再问一下，修改了php文件要重启apache 才生效？

**Comment by billge1205** [comment]
不用 可能是你apache有缓存吧 看下配置把缓存关了吧 
正常apache是不需要重启的

**Comment by rjzou** [comment]
修改php.ini opcache.enable=0 可以了。many thanks
