### ISSUE TITLE
jquery error and  scrollspy error

### ISSUE THREAD

**Issue by majiajia** [Tencent/Biny#30]
when i download the src code from github and try to run it ,it show error info that jquery is not defined and scrollspy id not defined.in demo.tpl.php

**Comment by billge1205** [comment]
in demo.tpl.php it will include footer.tpl.php and in footer.tpl it will load jquery.js and bootstrap.js in your src Folder /web/static/js/
if your demo not loaded js . you can try visit url http://{your host}/static/js/jquery.min.js and check the config of nginx

**Comment by billge1205** [comment]
Or you should open the short_open_tag in php.ini to use the native abbreviated rendering method.
it will make the include function work

**Comment by majiajia** [comment]
ok.thank you
