### ISSUE TITLE
TXService 思路不友好

### ISSUE THREAD

**Issue by Echosong** [Tencent/Biny#31]
TXService 工厂DAO 写法对 IDE 很不友好，开发会带来很多麻烦。不像静态语言可以定义类型，这种设计有点蹩脚

**Comment by billge1205** [comment]
开发中代码联想的确对IDE 有要求 这边一般都是在baseAction 或者 baseService 中添加@property使IDE可以正确联想 例如这个demo
![default](https://user-images.githubusercontent.com/13842960/31539514-53790dce-b03b-11e7-9e99-347efdc2653e.png)

**Comment by billge1205** [comment]
我们这边开发一般都有PHPSTORM 其他的IDE没有试过 但的确是有这个问题 之后会想想做一下优化
