### ISSUE TITLE
请问一下Service的用法是怎样的

### ISSUE THREAD

**Issue by lordGuan** [Tencent/Biny#32]
从demo中的loginAction，操作数据库是直接调用DAO。而privilegeService感觉更像是横切的一个通用业务逻辑层。能否稍稍讲解一下Service的用法。

**Comment by billge1205** [comment]
action 可以调用 service 和 dao 用法跟dao是一样的 都是可以通过 $this->xxxService 来使用
service 中也可以通过 $this->xxxDAO 来调用数据库
如果你的IDE没有代码提示的话 可以在class上面添加 @property 来让IDE认识service对象
可以参考示例：http://www.billge.cc/#overview-level

**Comment by billge1205** [comment]
privilegeService 这个文件的确是被框架特殊用了 作为鉴权的通过逻辑处理了
用户自定义Service文件可以在 /app/service/ 目录下自行创建使用

**Comment by lordGuan** [comment]
感谢~明白了，仍然是Controller-Service-DAO的结构（这就很方便我把原有的JavaWeb项目进行移植了
