### ISSUE TITLE
开启事务后，怎么捕获事务中的异常呢？

### ISSUE THREAD

**Issue by peizhijie** [Tencent/Biny#35]
请问`TXDatebase::start()`开启事务后，怎么捕获事务中的异常呢？然后进行针对异常的逻辑处理

**Comment by billge1205** [comment]
开启后执行update delete等方法会返回成功或者失败 如果失败的话可以通过 TXDatabase::rollback() 回滚整个事务 如果都没问题的话 执行TXDatabase::commit()方法 提交整个事务处理
