### ISSUE TITLE
请问开启了路由之后静态资源怎么访问 ==

### ISSUE THREAD

**Issue by Kavf** [Tencent/Biny#36]
我想访问../../../web/static/css/main.css
结果访问不了
程序报错 Fatal error:  Autoload file[app\controller\webAction] is fails in
大神，这个怎么解决啊

**Comment by billge1205** [comment]
如果nginx 或者 apache配置正确的话 直接访问 http://yourhost/static/css/main.css
或者使用php变量<?=$webRoot?>/static/css/main.css
具体配置看wiki文档 http://www.billge.cc

**Comment by billge1205** [comment]
使用php变量<?= $webRoot?>/static/css/main.css

**Comment by billge1205** [comment]
php变量 $webRoot 一直被github吃了

**Comment by Kavf** [comment]
@billge1205 蟹蟹
