### ISSUE TITLE
model 下 Person.php 这个文件名应该是小写的吧

### ISSUE THREAD

**Issue by flydo228** [Tencent/Biny#38]
类名是 ```person```，文件名却是 ```Person``` 。导致demo就出错了。后来把文件名改成小写就好了。

**Comment by billge1205** [comment]
谢谢提醒 的确是windows下改动大小不敏感导致的 会马上修复

**Comment by domyhero** [comment]
为什么类名要弄成小写呢？一般不都是大写嘛

**Comment by billge1205** [comment]
Biny 中model数据层 文件名 类名 参数名是保持一致的 类似person模型
TXApp::$model->person 对应 /model/person.php 中的 person类
用户也可以根据自己的习惯 命名自定义模型

**Comment by flydo228** [comment]
一般都首字母大写的吧。
可以```ucfirst```一下

**Comment by billge1205** [comment]
恩是的 框架原本有历史包袱 一直没调整 开源了之后会尽可能按照psr-4规范来优化

**Comment by tanteng** [comment]
可能由于历史包袱，感觉很多地方很陈旧，希望慢慢优化，能够体现现代化的PHP开发规范，加油！
