### ISSUE TITLE
关于权限 privilege，回调请求不到。

### ISSUE THREAD

**Issue by flydo228** [Tencent/Biny#40]
写成私有类的。所以报错了。

**Comment by billge1205** [comment]
其实是在报错前已经走了你的回调了 你可以在你的回调中die(); 终止掉 不终止的话系统会默认抛出异常
报错信息可以在index.php 中开关 SYS_DEBUG

**Comment by billge1205** [comment]
非debug模式下 会返回一个error页面 在config.php中可以配置
