### ISSUE TITLE
视图中绑定参数问题

### ISSUE THREAD

**Issue by David3310273** [Tencent/Biny#44]
如果按照新版的配置```'paramsType'] => 'one'```，该怎样用display在视图中绑定参数?

**Comment by billge1205** [comment]
在action中 `return $this->display('view', ['aa'=>1,'bb'=>2]);`
然后在view.tpl中 可以通过 `<?=$PRM['aa']?>` 获取
PRM的名称也可以在config.php 中 配置paramsKey

**Comment by billge1205** [comment]
参数有两种用法
`<?=$PRM['aa']?>` 会自动做反xss注入保护
`<?=$PRM->aa?>` 则返回原始数据
多层数组数据也一样 具体参考[](http://www.billge.cc/#view-xss)

**Comment by David3310273** [comment]
为什么不沿用之前`'paramsType' => 'keys'`中的做法直接extract($this->params)呢？

**Comment by David3310273** [comment]
为什么不再直接```extract($this->params)```了？

**Comment by billge1205** [comment]
如果这样 那就不具备 反xss的功能了 
现在的页面渲染是可以不依赖开发习惯 完全屏蔽xss注入的

**Comment by David3310273** [comment]
好的，谢谢
