### ISSUE TITLE
额，我又来提问了，大神帮我看看这是怎么回事

### ISSUE THREAD

**Issue by Kavf** [Tencent/Biny#47]
`

<pre><b>Fatal error</b>:  System Error [PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_pdo_mysql.dll' - /usr/lib/php/20151012/php_pdo_mysql.dll: cannot open shared object file: No such file or directory] in <b>/home/kang/product/kwms/lib/TXApp.php</b>:<b>153</b>
--
  | Stack trace:
  | #0 [internal function]: TXApp::handleFatalError()
  | #1 {main}

`

有时候刷新一下页面，在页面的最底部会现这个，然后在刷新一下就又没有了，请问这是怎么回事啊，是不是我的环境配置有问题。
Apache/2.4.18 (Ubuntu)
php 7.0.22
mysql  5.7.20-0ubuntu0.16.04.1

**Comment by billge1205** [comment]
挺奇怪的 ubuntu的系统里为啥会去调用dll文件
dll文件是windows才有的动态链接库
你是不是把windows下的东西装到ubuntu系统下了 具体我也是不是很清楚呢

**Comment by naofbear** [comment]
你是在unbuntu的 php.ini 中 load extension = php_pdo_mysql.dll 了吧。

**Comment by Kavf** [comment]
@billge1205 @naofbear 谢谢，已经解决了，的确是linux开启了dll扩展的原因，linux下php的配置是按文件夹存放的，php.ini里面开启dll配置不起作用
