### ISSUE TITLE
Biny里面能不能出个API授权机制

### ISSUE THREAD

**Issue by Kavf** [Tencent/Biny#48]
最近想开放一些接口让外部网站调用，但是不知道接口怎么写好些，比如身份认证，请求时间、次数限制，接口访问权限控制，不同身份的请求只能访问与之对应的接口，大神能不能在biny里面写一个让我参考下啊。。

**Comment by billge1205** [comment]
API规则实现方式很多 大体的思路都是 
给使用方分配私钥 然后把参数，时间和私钥进行一个摘要签名 
服务器端也进行相同操作 然后比对签名
这类功能不建议在框架层面封装 业务层还是自己实现吧 可以写在privilege里进行统一鉴权
