### ISSUE TITLE
Biny框架能否给一两个案列参考下

### ISSUE THREAD

**Issue by filecenter** [Tencent/Biny#51]
或者录制一两节视频，让我们这些小白期待已久的也能入手练练

**Comment by billge1205** [comment]
其实帮助文档写的挺详细的 http://www.billge.cc
把git上源码下下来通过nginx或者apache配置好(wiki里有) 本身就是个demo示例了 
Biny是一个很容易上手的轻量级框架 相信结合wiki你很快就会掌握的

**Comment by filecenter** [comment]
我是小白第一次使用看文档也不怎么理解

**Comment by billge1205** [comment]
谢谢你的建议 只是暂时还没有这方面的计划 抱歉
