### ISSUE TITLE
建议修改掉短标签

### ISSUE THREAD

**Issue by sn01615** [Tencent/Biny#53]
```
<? include TXApp::$view_root . "/base/common.tpl.php" ?>
```

**Comment by billge1205** [comment]
这里需要打开php.ini中的 short_open_tag
Biny用的是原生的tpl模版 简写会方便很多
不过这也属于个人习惯

**Comment by billge1205** [comment]
如果你说的是替换成{}之类的 也考虑过 但IDE不认识对开发效率上还是影响很大的

**Comment by sn01615** [comment]
short_open_tag 默认没有开启的 感觉用<?php 好点 虽然比较难看，这个比较少人开启吧，会成为使用阻碍
