### ISSUE TITLE
有没有文件上传的相关案例

### ISSUE THREAD

**Issue by lordGuan** [Tencent/Biny#55]
麻烦简单说框架内文件上传的操作流程

**Comment by billge1205** [comment]
前端：文件上传比较传统的就是form表单提交，也可以使用js控件异步提交（本质上还是表单）
后端：Biny没有对文件进行获取封装，原生的也很简单。直接 $_FILES[name] 就能获取到
没记错的话 $_FILES[name]['tmp_name'] 就是临时存放位置 用fopen就获取到整个文件流

**Comment by lordGuan** [comment]
ok~
