### ISSUE TITLE
TXLogger::addError向外抛错

### ISSUE THREAD

**Issue by lordGuan** [Tencent/Biny#56]
本来就想catch里打日志，这可咋整

**Comment by billge1205** [comment]
你先确认下是什么错误 index.php里把debug打开 页面里会返回错误信息的 我估计是 log目录没有写权限

**Comment by lordGuan** [comment]
addError里面的REQUEST的getUrl可能会抛6000，注释上注明抛错导致编译器提示了没有捕捉

**Comment by billge1205** [comment]
额 好吧 其实不用管就行了 正常走不到6000的 只有完全获取不到REQUEST信息的时候才会，这边还从来没遇到过

**Comment by lordGuan** [comment]
我也是这么想的，看起来有点儿难受

**Comment by billge1205** [comment]
其实并不建议在Biny中对系统Exception进行catch捕获 
Biny本身有写error log 的机制，而且当有异常时 debug模式下会在浏览器返回详细错误 而非debug模式下会返回一个提示页面
如果需要对Exception进行特殊处理 可以全局绑定Exception事件来处理
`TXEvent::on(onException, $your_class_method);`

**Comment by lordGuan** [comment]
对啊，忘了这个茬儿了，多谢提醒
