### ISSUE TITLE
在wiki的demo中，privilegeService.php中这个$this->correct()不存在

### ISSUE THREAD

**Issue by yuntianhev** [Tencent/Biny#58]
public function my_required($action, $key)
    {
        if($key){
            return$this->correct();
        }else{
            return $this->error('key not exists');
        }
    }

**Comment by billge1205** [comment]
correct()方法实际就是return true 的一层封装 觉得没必要就删除了 wiki没有及时更新 这边直接改成return true就行
谢谢你的提醒 wiki会及时修改

**Comment by tianheyunvip** [comment]
好的，
