### ISSUE TITLE
大神在index.php中isMaintenance = TRUE，貌似没有作用，求解，谢谢

### ISSUE THREAD

**Issue by yuntianhev** [Tencent/Biny#59]
//判断是否维护中
        if (isMaintenance){
         return $this->display('Main/maintenance');
        }

**Comment by billge1205** [comment]
我的错 改成这样吧
`//判断是否维护中
        if (isMaintenance){
            echo $this->display('Main/maintenance');
            exit;
        }`

**Comment by tianheyunvip** [comment]
好的，谢谢
