### ISSUE TITLE
模板渲染问题

### ISSUE THREAD

**Issue by mikemintang** [Tencent/Biny#6]
/lib/business/TXResponse.php中的这段代码读取缓冲区内容不稳定，导致前端页面渲染失败：

```
        ob_start();
        //include template
        $lang = TXLanguage::getLanguage();
        $file = sprintf('%s/template/%s%s.tpl.php', TXApp::$app_root, $this->view, $lang ?'.'.$lang : "");
        if (!is_readable($file)){
            $file = sprintf('%s/template/%s.tpl.php', TXApp::$app_root, $this->view);
        }
        if (!is_readable($file)){
            throw new TXException(2005, $this->view);
        }
        include $file;
        TXLogger::showLogs();

        $content = ob_get_clean();
        return $content;
```

<img width="824" alt="1" src="https://user-images.githubusercontent.com/9711570/30974997-ab991a24-a4a3-11e7-9d08-898d1c4f43db.png">

**Comment by billge1205** [comment]
看起来像是php.ini配置上的问题 框架运用在很多项目中并没有这种情况 你可以尝试打开opcache 可能会有作用

**Comment by billge1205** [comment]
或者可能跟php最大缓冲池的配置有关 www.billge.cc wiki文档 应该不会出现模版异常的情况 wiki就是用biny写的

**Comment by billge1205** [comment]
我知道了 php.ini里打开 short_open_tag就行了 因为biny里模版用的都是简写

**Comment by David3310273** [comment]
` 
/**
     * 获得模板渲染后的内容
     * @return string
     * @throws TXException
     */
    public function getContent()
    {
        if ($this->config['paramsType'] == 'keys'){
            //老版本兼容过滤XSS
            foreach ($this->params as $key => &$param) {
                if (!in_array($key, $this->objects)){
                    if (is_string($param)){
                        $param = TXString::encode($param);
                    } else if (is_array($param)){
                        $param = new TXArray($param);
                    }
                }
            }
            unset($param);
            extract($this->params);
        } else {
            if (!isset($this->config['objectEncode']) || $this->config['objectEncode']){
                //防XSS注入
                foreach ($this->objects as &$object) {
                    if (is_string($object)){
                        $object = $this->encode($object);
                    } elseif (is_array($object)) {
                        $object = new TXArray($object);
                    }
                }
                unset($object);
            }
            $key = $this->config['paramsKey'];
            $this->objects[$key] = new TXArray($this->params);
            // extract($this->params); //为什么这里不直接初始化params参数到视图中，而要封装进$objects属性中？
            extract($this->objects);
        }
        ...
`
