### ISSUE TITLE
这个地方的路由怎么实现的

### ISSUE THREAD

**Issue by filecenter** [Tencent/Biny#64]
![qq 20180113131959](https://user-images.githubusercontent.com/32012518/34903085-acfb3c34-f864-11e7-8b49-8c7c5b2a7cb1.png)

**Comment by billge1205** [comment]
这里只是根据登陆态跳转到/login 逻辑在previlegeService 的login_require里

**Comment by filecenter** [comment]
比如我创建Home的控制器怎样配置Home的路由呢？

**Comment by billge1205** [comment]
默认规则的路由不用配置
/Home => HomeAction 中的 action_index
/Home/method => HomeAction 中的 action_method

**Comment by filecenter** [comment]
我按照这http://www.billge.cc/demo/#router-rule里去做不能实现呀？

**Comment by billge1205** [comment]
发一下你的目录结构和请求的url 另外nginx是否配置正确 还有路由是需要大小写全匹配的

**Comment by billge1205** [comment]
还有看下返回什么错误 如果是nginx报错 那可能跟nginx配置有关 
参考http://www.billge.cc/#overview-index
如果是php报错 麻烦发一下错误信息

**Comment by filecenter** [comment]
我重新配置了一下出现500的报错

**Comment by billge1205** [comment]
错误信息发下

**Comment by filecenter** [comment]
解决了，从头到尾都是我的Apache 配置不对

**Comment by billge1205** [comment]
好的 有问题和建议欢迎随时交流

**Comment by filecenter** [comment]
还有个小问题，logs目录里面我全部清空了，访问一次首页又会出现一个错误的日志文件是什么情况，还是我的配置有问题吗？

**Comment by billge1205** [comment]
日志文件是默认一直会记录的 包括请求的信息以及错误的信息(默认会记录Notice级别以上的错误) /config/config.php中errorLevel 可以配置错误级别

**Comment by filecenter** [comment]
正常应该是一个log_2018-01-13.log
![qq 20180113184411](https://user-images.githubusercontent.com/32012518/34905366-094f7d42-f892-11e7-8e79-4e72962685bd.png)

**Comment by billge1205** [comment]
你可以打开看下有些什么错误 输出级别可以在config.php中控制

**Comment by filecenter** [comment]
这是什么错误？
![qq 20180113192132](https://user-images.githubusercontent.com/32012518/34905591-20b80dc8-f897-11e7-932e-68c206541e36.png)

**Comment by billge1205** [comment]
这错误就是 (你的域名)/robots.txt 这个url 404了
可能是你页面或者apache请求的 你可以在 /web/目录下放一个robots.txt 让它能被请求到
