### ISSUE TITLE
哇！这路由，全路径无法访问

### ISSUE THREAD

**Issue by pdwl** [Tencent/Biny#73]
http://localhost/test/index/
直接404！伪静态加上去直接500

**Comment by billge1205** [comment]
你可以看下404是php返回的还是ngunx/apache返回的 
如果是前者 需要创建testAction.php 包含function action_index
如果是后者请参考wiki文档正确配置下nginx/apache

**Comment by pdwl** [comment]
windows环境下apache

.htaccess

<IfModule mod_rewrite.c>
  Options +FollowSymlinks -Multiviews
  RewriteEngine On
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteRule . index.php
</IfModule>

希望遇到相同问题的人，能看到吧！
