### ISSUE TITLE
怎样实现多模块

### ISSUE THREAD

**Issue by filecenter** [Tencent/Biny#78]
比如我要建立一个admin模块

**Comment by billge1205** [comment]
如果你是想要模块化开发的话 Biny暂时并没有这方面的架构设计
但只是想要创建一个admin模型的话，可以在/app/model/下创建admin模型，程序中使用`TXApp::$model->admin` 即可获取对应模型，详细文档可以参考[http://www.billge.cc/#other-model](url)
