### ISSUE TITLE
如何在from表单里面生成需要提交的路由地址？

### ISSUE THREAD

**Issue by void9main** [Tencent/Biny#80]
如何在from表单里面生成需要提交的路由地址？

**Comment by void9main** [comment]
比如indexAction中的action_login()方法，如何在html表单中action中生成相应的路由？要用哪个方法？

**Comment by billge1205** [comment]
indexAction action_login 对应 路由 /index/login
form 元素中用action=“/index/login” 即可 不过现在很少用form提交了 用ajax异步提交更普遍

**Comment by void9main** [comment]
嗯嗯，简单的一个小项目，不需要使用到ajax
