### ISSUE TITLE
createOrUpdate 只能依赖主键冲突？

### ISSUE THREAD

**Issue by sn01615** [Tencent/Biny#86]

**Comment by billge1205** [comment]
是的 主键冲突再更新的场景实际运用中比较频繁
insert第一个参数内容 当冲突时执行update第二个参数操作(第二个参数缺省等于第一个参数)

**Comment by sn01615** [comment]
https://github.com/Tencent/Biny/blob/bb9fd471031c5297a17fdfc36c882f299dd0bda2/app/dao/base/baseDAO.php#L141
这个缓存好像没有过期时间

**Comment by sn01615** [comment]
可以加个支持select后update or insert吗？

**Comment by billge1205** [comment]
缓存这个可以在db配置中加个缓存时长配置 我晚点支持下

**Comment by billge1205** [comment]
select后insert update 可以在业务代码中用事务逻辑自己实现 没必要封装在DAO中哈

**Comment by sn01615** [comment]
另外好像都是mysqli的能封装下支持pdo或mysqli吗？

**Comment by billge1205** [comment]
可以的 框架早期用的mysql 后来升级成mysqli pdo可以支持下的

**Comment by sn01615** [comment]
可以支持orderDesc、orderAsc方法吗？

**Comment by sn01615** [comment]
还有`order by field()`方法

**Comment by fyfyfyfy11** [comment]
你能别发了么这就是一个随便传传的东西傻子都知道一堆错------------------ 原始邮件 ------------------
发件人: "杨龙"<notifications@github.com>
发送时间: 2019年5月19日(星期天) 晚上9:06
收件人: "Tencent/Biny"<Biny@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [Tencent/Biny] createOrUpdate 只能依赖主键冲突？ (#86)



可以支持orderDesc、orderAsc方法吗？
 
&mdash;

**Comment by sn01615** [comment]
同时打扰这么多人确实不对，非常抱歉！
由于本人水平有限，希望能得到批评指正。

**Comment by billge1205** [comment]
已支持order by field() 用法
