### ISSUE TITLE
使用Biny框架被腾讯列为危险网站

### ISSUE THREAD

**Issue by Illyasviels** [Tencent/Biny#98]
`https://guanjia.qq.com/online_server/result.html?url=https%3A%2F%2Fxiv.acgme.cn`

**Comment by sn01615** [comment]
这特喵和Biny有何关系？

**Comment by billge1205** [comment]
![image](https://user-images.githubusercontent.com/13842960/70427362-8a4b2180-1aaf-11ea-9aca-3545407c8e3b.png)
Biny只是个框架 网站是否危险是跟业务功能相关的 请检查业务逻辑哈

**Comment by Illyasviels** [comment]
是的我知道，但是我使用以前的版本没有问题，但是用了最新版，腾讯直接报危险了。中途间隔时间不到5分钟。

**Comment by Illyasviels** [comment]
如果不是和框架有关的查杀就最好了，我还会排查详细内容，先关闭issue了。

**Comment by billge1205** [comment]
这个还是要联系腾讯电脑管家相关人员咨询具体原因，框架升级理论上对这些没有影响的
