### ISSUE TITLE
怎么下载干净的框架？

### ISSUE THREAD

**Issue by Tomorrowxxy** [Tencent/Biny#99]
直接github clone ？

**Comment by billge1205** [comment]
https://github.com/Tencent/Biny/releases

**Comment by Tomorrowxxy** [comment]
大佬回复好快啊
我clone了一份
目前遇到了两个问题
1. shell.php是做什么用的  运行了有报错

2.没看明白怎么使用api模式 
也添加了protected $restApi = true;
![UTOOLS1576220316616.png](https://img02.sogoucdn.com/app/a/100520146/bd16c8a607a587c0321d42d31bd71f8b)

**Comment by billge1205** [comment]
在服务器端执行要用shell模式 index.php 是web入口 shell模式用法见文档
http://www.billge.cc/#shell
restApi是web端 支持restful用的

**Comment by Tomorrowxxy** [comment]
也就是说shell调用的方法必须写到/app/shell/文件夹中   不可以调用/app/controller中的方法么

**Comment by billge1205** [comment]
controller 入口是分开的 service dao 还有基础类是公共的

**Comment by Tomorrowxxy** [comment]
好的 我在研究研究  还是没太搞明白  有微信群 or QQ群 or ... 么

**Comment by billge1205** [comment]
没有官方群 有问题issue里提吧
